version: '3.5'
services:
  discovery:
    image: piomin/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: piomin/gateway-service
    container_name: service-gateway
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  zipkin-service:
    image: piomin/zipkin-service
    container_name: zipkin-service
    build:
      context: ./zipkin-service
      dockerfile: Dockerfile
    ports:
      - "9411:9411"

  database:
    image: mysql-database
    container_name: database
    ports:
      - "3306:3306"
    links:
      - discovery

  restaurant-service:
    image: piomin/restaurant-service
    container_name: restaurant-service
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      "bootstrap.servers": kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      "spring.datasource.url": "jdbc:mysql://database:3306/soa"
    links:
      - discovery
      - database
      - kafka
    depends_on:
      - database
      - kafka

  order-service:
    image: piomin/order-service
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      "bootstrap.servers": "kafka:9092"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      "spring.datasource.url": "jdbc:mysql://database:3306/soa"
    links:
      - discovery
      - database
      - kafka
    depends_on:
      - database
      - kafka

  email-service:
    image: piomin/email-service:external
    container_name: email-service
#    build:
#      context: ./email-service
#      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      "bootstrap.servers": kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
      - kafka
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    links:
      - zookeeper
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order-email"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    expose:
      - "9093"